export interface AppColors {
  primary: string;
  primaryLight: string;
  secondary: string;
  secondaryLight: string;
  background: string;
  surface: string;
  surfaceSubtle: string;
  surfaceElevated: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  textInverse: string;
  border: string;
  borderStrong: string;
  danger: string;
  dangerLight: string;
  warning: string;
  warningLight: string;
  success: string;
  successLight: string;
  info: string;
  infoLight: string;
  shadow: string;
  // Tab bar
  tabBarBackground: string;
  tabBarActive: string;
  tabBarInactive: string;
  tabBarBorder: string;
}

export const AppTheme: Record<'light' | 'dark' | 'dennise', AppColors> = {
  light: {
    primary: '#1a73e8',
    primaryLight: '#dbeafe',
    secondary: '#3b82f6',
    secondaryLight: '#eff6ff',
    background: '#f8fafc',
    surface: '#ffffff',
    surfaceSubtle: '#f1f5f9',
    surfaceElevated: '#ffffff',
    text: '#0f172a',
    textSecondary: '#64748b',
    textTertiary: '#475569',
    textInverse: '#ffffff',
    border: '#e2e8f0',
    borderStrong: '#cbd5e1',
    danger: '#ef4444',
    dangerLight: '#fee2e2',
    warning: '#f59e0b',
    warningLight: '#fef3c7',
    success: '#10b981',
    successLight: '#d1fae5',
    info: '#6366f1',
    infoLight: '#e0e7ff',
    shadow: '#000000',
    tabBarBackground: '#ffffff',
    tabBarActive: '#1a73e8',
    tabBarInactive: '#94a3b8',
    tabBarBorder: '#e2e8f0',
  },
  dark: {
    primary: '#3b82f6',
    primaryLight: '#1e3a8a',
    secondary: '#60a5fa',
    secondaryLight: '#1e40af',
    background: '#0f172a',
    surface: '#1e293b',
    surfaceSubtle: '#334155',
    surfaceElevated: '#475569',
    text: '#f8fafc',
    textSecondary: '#94a3b8',
    textTertiary: '#cbd5e1',
    textInverse: '#ffffff',
    border: '#334155',
    borderStrong: '#475569',
    danger: '#f87171',
    dangerLight: '#450a0a',
    warning: '#fbbf24',
    warningLight: '#451a03',
    success: '#34d399',
    successLight: '#022c22',
    info: '#818cf8',
    infoLight: '#1e1b4b',
    shadow: '#000000',
    tabBarBackground: '#1e293b',
    tabBarActive: '#3b82f6',
    tabBarInactive: '#64748b',
    tabBarBorder: '#334155',
  },
  // EL TEMA SECRETO 🌸
  dennise: {
    primary: '#ec4899',
    primaryLight: '#fce7f3',
    secondary: '#f472b6',
    secondaryLight: '#fdf2f8',
    background: '#fff1f2',
    surface: '#ffffff',
    surfaceSubtle: '#fbcfe8',
    surfaceElevated: '#ffffff',
    text: '#831843',
    textSecondary: '#be185d',
    textTertiary: '#db2777',
    textInverse: '#ffffff',
    border: '#fbcfe8',
    borderStrong: '#f9a8d4',
    danger: '#e11d48',
    dangerLight: '#ffe4e6',
    warning: '#fbbf24',
    warningLight: '#fef3c7',
    success: '#10b981',
    successLight: '#d1fae5',
    info: '#ec4899',
    infoLight: '#fce7f3',
    shadow: '#be185d',
    tabBarBackground: '#fdf2f8',
    tabBarActive: '#ec4899',
    tabBarInactive: '#f9a8d4',
    tabBarBorder: '#fbcfe8',
  },
};